### ISSUE TITLE
Peer to peer code

### ISSUE THREAD

**Issue by banlon-jones** [rachidelaid/pokeDB#35]
Hi @rachidelaid and @guerreiropedr0 ,
Great job so far, you have clearly demonstrated your understanding of the project and ES6 concepts
- your folder structure is impressive :+1: 
- I Like the way you implemented pagination in your project, :clap: 
- Nothing to change so far 
Great job guys and keep up the good work :clap: 

<img src="https://media0.giphy.com/media/UDwUHzUGu6jdsWY5pC/giphy.gif"/>

**Comment by rachidelaid** [comment]
thank you @banlon-jones ❤️
